### ISSUE TITLE
Compliance Plugins Not Working

### ISSUE THREAD

**Issue by theresaperry95** [thechiragjogani/nessus#1]
Hi,

Thank you for developing this script. I've used it to successfully install Nessus Pro. However, although I'm able to successfully use this for normal scans, I haven't been able to get audit scans working, even after downloading and installing **audits.tar.gz**. I did the following after the installation:

```
curl -A Mozilla -o audits.tar.gz --url "https://www.tenable.com/downloads/api/v1/public/pages/download-all-compliance-audit-files/downloads/7472/download?i_agree_to_tenable_license_agreement=true" &>/dev/null
echo " o Installing audit plugins."
/opt/nessus/sbin/nessuscli update audits.tar.gz &>/dev/null
```

but the **Compliance Tab** still doesn't appear when I try to run a *Policy Compliance Auditing* scan. I even tried rebuilding the Nessus DB using:

```
sudo /opt/nessus/sbin/nessusd -R
```

but it still didn't show up. Any ideas? Have you been able to get it to work?

**Comment by thechiragjogani** [comment]
I have no idea about that.

**Comment by mthbrown** [comment]
Do you see the *Compliance Tab* in your version?
